apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "internal-app"
        vault.hashicorp.com/agent-inject-secret-db-creds: "database/static-creds/static"
        vault.hashicorp.com/agent-inject-template-db-creds: |
          {{- with secret "database/static-creds/static" -}}
          postgres://{{ .Data.username }}:{{ .Data.password }}@postgres:5432/postgres?sslmode=disable
          {{- end }}
    spec:
      serviceAccountName: app
      containers:
      - image: busybox
        name: busybox
        command:
        - "sh"
        - "-c"
        - "while true; do cat /vault/secrets/db-creds && sleep 60; done"
